---

- hosts: all
  become: true
  become_user: root 
  tasks: 
  
  - name: install apache2 package
    yum: 
       update_cache:yes
       
    when: ansible_distribution == "CentOS"     

  - name: install apache2 package
    yum:
       name: httpd
       state: latest
    when: ansible_distribution == "CentOS"

  - name: install apache2 package
    yum:
       name: php
       state: latest
    when: ansible_distribution == "CentOS"
  
...
